### ISSUE TITLE
errors in beliefPropStereo.m

### ISSUE THREAD

**Issue by harikiran2995** [muhammetbalcilar/Comparison-of-Disparity-Estimation-Algorithms#2]
blockmatching and dynamcc programming is wroking fine but there are some errors in this beliefPropStereo.m
i have given parameters in main.m for img iter ... 

thanks,

**Comment by balcilar** [comment]
I just rerun it and there is no error. Just run main.m script and let me know what error do you get. just copy all error messages here.

**Comment by harikiran2995** [comment]
https://drive.google.com/file/d/1UCUcXZWCKLtp46O2X2wHMnhQaXKVybMs/view?usp=sharing

i attached the error message in the link above

**Comment by balcilar** [comment]
ok it is because of old version Matlab's matrix dimension problem . I fixed it please donwload and test it again.

**Comment by harikiran2995** [comment]
thanks a lot

**Comment by harikiran2995** [comment]
still same issue
https://drive.google.com/file/d/1kfJktAG_05STBbhxB9XJEkwiCWYzs8Z6/view?usp=sharing

**Comment by harikiran2995** [comment]
which version of matlab required??

**Comment by balcilar** [comment]
check again please. I just updated it

**Comment by harikiran2995** [comment]
Thanks a lot now it's working fine!
